=== LXHlxj/springboot/target/classes/xml/xmldata.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT xmldatas (xmldata*,tablename*)>
<!ATTLIST xmldata  name CDATA #REQUIRED >
<!ATTLIST tablename  name CDATA #REQUIRED >
<!ELEMENT tablename (line*)>
<!ATTLIST line name CDATA #REQUIRED>
<!ATTLIST xmldatas  name CDATA  #REQUIRED >
<!ELEMENT xmldata (url,username,DriverClassName,password)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT DriverClassName (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT line (#PCDATA)>

=== LXHlxj/springboot/src/main/resources/xmldata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xmldatas SYSTEM "xmldata.dtd">
<xmldatas name="mysql">
<xmldata name="">
    <url>jdbc:mysql:///isql</url>
    <username>root</username>
    <DriverClassName>com.mysql.jdbc.Driver</DriverClassName>
    <password>lxhLXH15928659674</password>
</xmldata>
    <tablename name="">
        <line name=""></line>
        <line name=""></line>
        <line name=""></line>
        <line name=""></line>
        <line name=""></line>
        <line name=""></line>
        <line name=""></line>
        <line name=""></line>
    </tablename>
</xmldatas>
